version: "3.9"
services:
  web:
    image: "dan-test:latest"
    working_dir: '/app/frontend'
    entrypoint: ['npm', 'start']
    ports:
      - "3000:3000"
  api:
    image: "dan-test:latest"
    working_dir: '/app/backend'
    # entrypoint: ["sleep", "5000"]
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
  db:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD="password"
    ports:
      - "3306:3306"