# build environment
FROM node:13.12.0-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY frontend/package.json ./
RUN npm i
RUN npm install react-scripts@3.4.1 -g --silent

COPY frontend ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/frontend/build /usr/share/nginx/html
EXPOSE 80
USER 1001
CMD ["nginx", "-g", "daemon off;"]