version: "3.9"
services:
  web:
    image: "frontend:latest"
    ports:
      - "3000:80"
  api:
    image: "backend:latest"
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10



  # Messing around with dev stuff
  # web:
  #   image: "dan-test:latest"
  #   working_dir: '/app/frontend'
  #   entrypoint: ['npm', 'start']
  #   ports:
  #     - "3000:3000"
  # api:
  #   image: "dan-test:latest"
  #   working_dir: '/app/backend'
  #   entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  #   ports:
  #     - "8000:8000"
  # db:
  #   image: "mysql:8"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD="password"
  #   # ports:
  #   #   - "3306:3306"