apiVersion: apps/v1
kind: Deployment
metadata:
  name: goback-deployment
  labels:
    app: goback
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goback
  template:
    metadata:
      labels:
        app: goback
    spec:
      containers:
      - name: goback
        image: goback:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SYMBOL
          value: "MSFT"
        - name: NDAYS
          value: "7"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: goback-secret
              key: apikey
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: goback-secret
data:
  apikey: QzIyN1dEOVczTFVWS1ZWOQ==
---
apiVersion: v1
kind: Service
metadata:
  name: goback
spec:
  selector:
    app: goback
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          # servicename: goback
          # serviceport: 8080
          service:
            name: goback
            port:
              number: 8080